class Lexicon:
    instructions = "Instruktionen"
    no = "Nein"
    results = "Ergebnis"
    round_number = "Runde"
    start = "Start"
    stop = "Stopp"
    yes = "Yes"
    your_decision = "Ihre Entscheidung"
    not_at_all = "überhaupt nicht"
    very_much = "sehr stark"
    no_effort = "keinen Aufwand"
    great_deal_of_effort = "grossen Aufwand"
    not_at_all_important = "überhaupt nicht wichtig"
    extremely_important = "extrem wichtig"
    likely_increase = "Zunahme ist wahrscheinlich"
    no_change = "Keine Veränderung"
    likely_decrease = "Abnahme ist wahrscheinlich"
    dont_know = "Weiss nicht"

    #Climate Change Concern Tobler
    ccc_title = "Einstellungen zum Klimawandel"
    ccc_header = "Wie sehr stimmen Sie den folgenden Aussagen zu?"
    ccc1Label = "Wir müssen das empfindliche Klimagleichgewicht schützen."
    ccc2Label = "Der Klimaschutz ist wichtig für unsere Zukunft."
    ccc3Label = "Ich bin besorgt über den Zustand des Klimas."
    ccc4Label = "Der Klimawandel hat ernste Folgen für die Menschheit und die Natur."
    ccc10Label = "Der Klimawandel und seine Folgen werden in den Medien übertrieben dargestellt."
    ccc11Label = "Der Klimawandel ist in erster Linie Geschäftemacherei."
    ccc12Label = "Solange die Metereologie nicht mal das Wetter richtig vorhersagen kann, kann das Klima auch nicht zuverlässig vorhergesagt werden."
    ccc13Label = "Es gibt wichtigere Probleme als den Klimaschutz."
    ccc14Label = "Ich fühle mich von dem Klimawandel nicht bedroht."
    ccc15Label = "Die Folgen des Klimawandels sind unvorhersehbar, deswegen ist klimafreundliches Verhalten nutzlos."
    ccc16Label = "Klimaschutz verhindert unnötigerweise unser Wirtschaftswachstum."

    #Climate Change Emotion Knauf/Truelove
    cce_title =  "Einstellungen zum Klimawandel"
    cce_header = "Wenn ich an den Klimawandel danke, dann fühle ich..."
    cce1Label = "Wut"
    cce2Label = "Angst/Sorge"
    cce3Label = "Traurigkeit"
    cce4Label = "Freude"
    cce5Label = "Neugier"
    cce6Label = "Hoffnung"

    ### Injunctive / descriptive norms for global warming Goldberg et al
    gwn_title = "Einstellungen zum Klimawandel"
    gwn_header = "Welche Einstellung hat Ihr Umfeld zum Klimawandel?" #"What stance do people around you have towards climate change?"
    gwn1Label = "Wie viel Aufwand betreibt Ihre Familie und Ihre Freunde, um die Erderwärmung zu reduzieren?" #"How much of an effort do your family and friends make to reduce global warming?"
    gwn2Label = "Wie wichtig ist es für Ihre Familie und Ihre Freunde, dass Sie tätig werden, um die Erdwerärmung zu reduzieren?" #"How important is it to your family and friends that you take action to reduce global warming?"

    ### Climate Change Impact / Consequence Knowledge van der Linden 
    cck_title = "Wissen über den Klimawandel"
    cck_header = "Bitte geben Sie an, ob die folgenden Größen voraussichtlich aufgrund des Klimawandels größer, kleiner oder gleich bleiben werden."
    cck1Label = "Weltweiter Meeresspiegel"
    cck2Label = "Saurer Regen"
    cck3Label = "Schmelzen von Gletschern und Polarkappen"
    cck4Label = "Gebiete auf der Welt, die Dürre erleben"
    cck5Label = "Weltweite Ausbreitung von Infektionskrankheiten"
    cck6Label = "Luftverschmutzung"
    cck7Label = "Weltweite Durchschnittstemperatur"
    cck8Label = "Extreme Wetterereignisse (z. B. Überschwemmungen, Hurrikane usw.)"
    cck9Label = "Weltweite Artenvielfalt (d. h. Vielfalt von Pflanzen und Tieren)"
    cck10Label = "Vulkanische Eruptionen"
    cck11Label = "Das Loch in der Ozonschicht"
    cck12Label = "Häufigkeit von heißen Tagen und Nächten"
    cck13Label = "Weltweiter Süßwasservorrat"