class Lexicon:
    instructions = "Instruktionen"
    no = "Nein"
    results = "Ergebnis"
    round_number = "Runde"
    start = "Start"
    stop = "Stopp"
    yes = "Ja"
    your_decision = "Ihre Entscheidung"
    not_at_all = "gar nicht"
    very_much = "sehr stark"
    no_effort = "keinen Aufwand"
    great_deal_of_effort = "grossen Aufwand"
    not_important = "nicht wichtig"
    not_at_all_important = "überhaupt nicht wichtig"
    extremely_important = "extrem wichtig"
    likely_increase = "Zunahme ist wahrscheinlich"
    no_change = "Keine Veränderung"
    likely_decrease = "Abnahme ist wahrscheinlich"
    dont_know = "Weiss nicht"
    opposed_to_values = "meinen Werten entgegengesetzt"
    strongly_liberal = "stark liberal"
    somewhat_liberal = "eher liberal"
    moderate = "moderat"
    somewhat_conservative = "eher konservativ"
    strongly_conservative = "stark konservativ"
    no_trust_at_all = "überhaupt kein Vertrauen"
    full_trust = "volles Vertrauen"
    completely_false = "komplett falsch"
    completely_true = "komplett richtig"

    #Climate Change Concern Tobler
    ccc_title = "Einstellungen zum Klimawandel"
    ccc_header = "Wie sehr stimmen Sie den folgenden Aussagen zu?"
    ccc1Label = "Wir müssen das empfindliche Klimagleichgewicht schützen."
    ccc2Label = "Der Klimaschutz ist wichtig für unsere Zukunft."
    ccc3Label = "Ich mache mir Sorgen über den Zustand des Klimas."
    ccc4Label = "Der Klimawandel hat ernste Folgen für die Menschheit und die Natur."
    ccc10Label = "Der Klimawandel und seine Folgen werden in den Medien übertrieben."
    ccc11Label = "Der Klimawandel ist ein betrügerisches Geschäft."
    ccc12Label = "Solange Metereologen nicht einmal richtig das Wetter vorhersagen können, kann das Klima auch nicht zuverlässig vorhergesagt werden."
    ccc13Label = "Es gibt wichtigere Probleme als den Klimaschutz."
    ccc14Label = "Ich fühle mich nicht von dem Klimawandel bedroht."
    ccc15Label = "Die Folgen des Klimawandels sind unvorhersehbar, deswegen ist mein klimafreundliches Verhalten vergeblich."
    ccc16Label = "Klimaschutz behindert unnötigerweise das Wirtschaftswachstum."

    #Climate Change Emotion Knauf/Truelove
    cce_title =  "Einstellungen zum Klimawandel"
    cce_header = "Wenn ich an den Klimawandel denke, dann fühle ich..."
    cce1Label = "Wut"
    cce2Label = "Angst"
    cce3Label = "Traurigkeit"
    cce4Label = "Freude"
    cce5Label = "Neugier"
    cce6Label = "Hoffnung"

    ### Climate Change Impact / Consequence Knowledge van der Linden is out different items
    cck_title = "Wissen über den Klimawandel"
    cck_header = "Bitte geben Sie an, ob die folgenden Größen voraussichtlich aufgrund des Klimawandels größer, kleiner oder gleich bleiben werden."
    cck1Label = "Weltweiter Meeresspiegel"
    cck2Label = "Saurer Regen"
    cck3Label = "Schmelzen von Gletschern und Polarkappen"
    cck4Label = "Gebiete auf der Welt, die Dürre erleben"
    cck5Label = "Weltweite Ausbreitung von Infektionskrankheiten"
    cck6Label = "Luftverschmutzung"
    cck7Label = "Weltweite Durchschnittstemperatur"
    cck8Label = "Extreme Wetterereignisse (z. B. Überschwemmungen, Hurrikane usw.)"
    cck9Label = "Weltweite Artenvielfalt (d. h. Vielfalt von Pflanzen und Tieren)"
    cck10Label = "Vulkanische Eruptionen"
    cck11Label = "Das Loch in der Ozonschicht"
    cck12Label = "Häufigkeit von heißen Tagen und Nächten"
    cck13Label = "Weltweiter Süßwasservorrat"

    # (Dis)trust in Climate Science Sarathchandra & Haltinner is out
    cst_title = "Meinung zu Klimawissenschaft"
    cst_header = "Wie sehr stimmen Sie den folgenden Aussagen zu?"
    cst1Label = "Klimawissenschaftler haben nicht genug Daten, um zu wissen, dass der vom Menschen verursachte Klimawandel existiert."
    cst2Label = "Klimawissenschaftler sind nicht offen bei ihrer Forschung."
    cst3Label = "Klimawissenschaftler ignorieren diejenigen, die anderer Meinung sind."
    cst4Label = "Wissenschaftliche Zeitschriften veröffentlichen nur Artikel, die zu dem Schluss kommen, dass der Klimawandel existiert."
    cst5Label = "Es gibt keinen wissenschaftlichen Konsens darüber, dass der vom Menschen verursachte Klimawandel existiert."
    cst6Label = "Der Klimawissenschaft kann man nicht trauen."

    # Personal efficacy Leiserowitz et al, 2010
    pe_title = "Einstellungen zum Klimawandel"
    pe_header = "Wie sehr stimmen Sie den folgenden Aussagen zu?"
    pe1Label = "Die Handlungen eines einzelnen Individuums werden keinen Unterschied beim Klimawandel machen."
    pe2Label = "Einzelne Personen können den Klimawandel und seine Auswirkungen beeinflussen."
    pe3Label = "Die Handlungen Einzelner beeinflussen andere dazu, sich so zu verhalten, dass die Auswirkungen der globalen Erwärmung gemildert werden."

    # Worldviews and values - Hierarchy-Egalitarianism & Individualism-Communitarianism
    wvv_title = "Wie sehen Sie die Welt?"
    wvv_header = "Wie sehr stimmen Sie den folgenden Aussagen zu?"
    wvv1Label = "Unsere Gesellschaft wäre besser dran, wenn der Reichtum gleichmäßiger verteilt wäre."
    wvv2Label = "Viele Probleme in unserer Gesellschaft resultieren aus dem Verschwinden des traditionellen Familienbildes, in der der Mann arbeitet und die Frau zu Hause bleibt."
    wvv3Label = "Diskriminierung von Minderheiten ist in unserem Land immer noch ein sehr ernstes Problem."
    wvv4Label = "Die Regierung mischt sich viel zu sehr in unseren Alltag ein."
    wvv5Label = "Ich finde, dass erfolgreiche Geschäftsleute das Recht haben, ihren Reichtum so auszukosten, wie sie es für richtig halten."
    wvv6Label = "Zu viele Menschen erwarten, dass die Gesellschaft Dinge für sie tut, die sie selbst tun sollten."

    # Importance of biospheric values van der Linden, 2015
    ibv_title = "Wichtige Prinzipien in Umweltfragen"
    ibv_header = "Wie wichtig sind Ihnen die folgenden Werte als generelle Leitprinzipien in Ihrem Leben?"
    ibv1Label = "Respektieren der Erde (Harmonie mit anderen Arten)"
    ibv2Label = "Schützen der Umwelt (die Natur erhalten)"
    ibv3Label = "Verhindern von Umweltverschmutzung (natürliche Ressourcen schützen)"
    ibv4Label = "Einheit mit der Natur (sich in die Natür einfügen)"

    # Political Orientation Pennycook et al 2020
    po_title = "Politische Ausrichtung"
    po_header = "Was ist Ihre allgemeine Haltung zu politischen Themen?"
    po1Label = "Bei sozialen Themen bin ich..."
    po2Label = "Bei wirtschaftlichen Themen bin ich..."

    # Trust in political institutions from Eurobarometer / Lantian et al 2016
    pit_title = "Wie stark ist Ihr Vertrauen in öffentliche Institutionen?"
    pit_header = "Wie viel Vertrauen haben Sie jeweils in in die folgenden Insitutionen?"
    pit1Label = "Die Regierung"
    pit2Label = "Regionale oder lokale Behörden"
    pit3Label = "Justiz und Rechtssystem"
    pit4Label = "Die Medien"
  
    ### Demographics
    demographics_title = "Persönliche Daten"
    demographics_header = "Bitte geben Sie die folgenden Informationen über sich ein."

    age_label = "Wie alt sind Sie?"
    gender_label = "Welchem Geschlecht fühlen Sie sich zugehörig?"
    female = "Weiblich"
    male = "Männlich"
    diverse = "Divers"
    other = "Andere"

    income_label = "Was ist Ihr jährliches Einkommen?"
    income_less_than_A = "Weniger als 25.000 $"
    income_A_to_B = "25.000 $ - 50.000 $"
    income_B_to_C = "50.001 $ - 75.000 $"
    income_C_to_D = "75.001 $ - 100.000 $"
    income_more_than_D = "Mehr als 100.000 $"
    prefer_not_to_say = "Keine Angabe"

    education_label = "Was ist Ihr höchster Bildungsabschluss?"
    no_formal_education = "Keine formale Bildung"
    elementary_school = "Grundschule"
    secondary_school = "Hauptschulabschluss"
    higher_secondary_school = "Mittlere Reife"
    vocational_training = "Berufsausbildung"
    high_school = "Abitur"
    college_degree = "Hochschulabschluss - Bachelor"
    master_degree = "Hochschulabschluss - Master"
    doctoral_degree = "Promotion"
    prefer_not_to_say_education = "Keine Angabe"

    residential_area_label = "Was beschreibt Ihre Wohngegend am besten?"
    metropolitan_area = "Metropole/Großstadt"
    suburban = "Kleinstadt"
    rural = "Ländliche Gegend"

    zip_code_label = "PLZ (freiwillig)"

    party_affiliation_label = "Welcher Partei würden Sie am ehesten Ihre Stimme geben?"
    cdcsu = "CDU/CSU"
    spd = "SPD"
    gruene = "Bündnis 90/Die Grünen"
    fdp = "FDP"
    linke = "Die Linke"
    afd = "Alternative für Deutschland (AfD)"
    other_party = "Andere"
