class Lexicon:
    instructions = "Instruktionen"
    no = "Nein"
    results = "Ergebnis"
    round_number = "Runde"
    start = "Start"
    stop = "Stopp"
    yes = "Yes"
    your_decision = "Ihre Entscheidung"
    not_at_all = "überhaupt nicht"
    very_much = "sehr stark"

    #Climate Change Concern Tobler
    ccc_title = "Einstellungen zum Klimawandel"
    ccc_header = "Wie sehr stimmen Sie den folgenden Aussagen zu?"
    ccc1Label = "Wir müssen das empfindliche Klimagleichgewicht schützen."
    ccc2Label = "Der Klimaschutz ist wichtig für unsere Zukunft."
    ccc3Label = "Ich bin besorgt über den Zustand des Klimas."
    ccc4Label = "Der Klimawandel hat ernste Folgen für die Menschheit und die Natur."
    ccc10Label = "Der Klimawandel und seine Folgen werden in den Medien übertrieben dargestellt."
    ccc11Label = "Der Klimawandel ist in erster Linie Geschäftemacherei."
    ccc12Label = "Solange die Metereologie nicht mal das Wetter richtig vorhersagen kann, kann das Klima auch nicht zuverlässig vorhergesagt werden."
    ccc13Label = "Es gibt wichtigere Probleme als den Klimaschutz."
    ccc14Label = "Ich fühle mich von dem Klimawandel nicht bedroht."
    ccc15Label = "Die Folgen des Klimawandels sind unvorhersehbar, deswegen ist klimafreundliches Verhalten nutzlos."
    ccc16Label = "Klimaschutz verhindert unnötigerweise unser Wirtschaftswachstum."