class Lexicon:
    instructions = "Instructions"
    no = "No"
    results = 'Results'
    round_number = "Round no."
    start = "Start"
    stop = "Stop"
    yes = "Yes"
    your_decision = "Your decision"
    not_at_all = "not at all"
    very_much = "very much"
    no_effort = "no effort"
    great_deal_of_effort = "a great deal of effort"
    not_at_all_important = "not at all important"
    extremely_important = "extremely important"
    likely_increase = "Likely to Increase"
    no_change = "No Change"
    likely_decrease = "Likely to Decrease"
    dont_know = "Don't know"


    #Climate Change Concern Tobler
    ccc_title = "Attitudes about Climate Change"
    ccc_header = "How much do you agree with the following statements?"
    ccc1Label = "We must protect the climate’s delicate equilibrium."
    ccc2Label = "Climate protection is important for our future."
    ccc3Label = "I worry about the climate’s state."
    ccc4Label = "Climate change has severe consequences for humans and nature."
    ccc10Label = "Climate change and its consequences are being exaggerated in the media."
    ccc11Label = "Climate change is a racket."
    ccc12Label = "As long as meteorologists are not even able to accurately forecast weather, climate cannot be reliably predicted either."
    ccc13Label = "There are larger problems than climate protection."
    ccc14Label = "I do not feel threatened by climate change."
    ccc15Label = "The impacts of climate change are unpredictable; thus, my climate-friendly behavior is futile."
    ccc16Label = "Climate protection needlessly impedes economic growth."


    #Climate Change Emotion Knauf/Truelove
    cce_title = "Attitudes about Climate Change"
    cce_header = "When I think of Climate Change I feel..."
    cce1Label = "Anger"
    cce2Label = "Fear/Worry"
    cce3Label = "Sadness"
    cce4Label = "Joy"
    cce5Label = "Curiosity"
    cce6Label = "Hope"

    ### Injunctive / descriptive norms for global warming Goldberg et al
    gwn_title = "Attitudes about Climate Change"
    gwn_header = "What stance do people around you have towards climate change?"
    gwn1Label = "How much of an effort do your family and friends make to reduce global warming?"
    gwn2Label = "How important is it to your family and friends that you take action to reduce global warming?"

    ### Climate Change Impact / Consequence Knowledge van der Linden 
    cck_title = "Climate Change Knowledge"
    cck_header = "Please indicate whether each of the following is likely to increase, decrease or not change at all as a result of climate change."
    cck1Label = "Global sea level"
    cck2Label = "Acid rain"
    cck3Label = "Melting of glaciers and polar ice caps"
    cck4Label = "Areas in the world experiencing drought" 
    cck5Label = "Global spread of infectious disease"
    cck6Label = "Air pollution" 
    cck7Label = "Global average temperature" 
    cck8Label = "Extreme weather events (e.g., flooding, hurricanes, etc.)" 
    cck9Label = "Global biodiversity (i.e., variety of plants and animals)"
    cck10Label = "Volcanic eruptions" 
    cck11Label = "The hole in the ozone layer" 
    cck12Label = "Frequency of hot days and nights" 
    cck13Label = "Global fresh water supply"