class Lexicon:
    Title_affectiveImagery = "Associations towards a Carbon Tax"
    Instr_affectiveImagery = "Before we start with our task, we would like to ask you to write down at least one word or thought that comes to your mind when you think of the term 'Carbon Tax'."
    Association1 = "1. Association"
    Association2 = "2. Association"
    Association3 = "3. Association"
    Association4 = "4. Association"

    # Affective Imagery Rating
    Title_rating = "Your associations regarding the carbon tax"
    Instructions_rating = "Below you can find the words and thoughts you have mentioned in connection with the carbon tax. Please indicate how positive or negative these associations are in relation to the carbon tax."
    very_negative = "Very negative (1)"
    very_positive = "Very positive (7)"

    # Instructions on Task 
    Title_Instructions = "Instructions on your task"
    Text_Instructions = "<p>Climate change and the warming of the planet is progressing rapidly, mainly due to human induced greenhouse gases such as carbon dioxide (CO<sub>2</sub>). <br> </p> <p> One way to tackle this is with a 'carbon tax.' <br> A carbon tax is a fee on the carbon dioxide (CO<sub>2</sub>) emissions that come with the production and consumption of various products and activities. This includes, but is not limited to, fossil fuels, agricultural products like meat and dairy, and industrial processes. It has the goal to make people and businesses reduce their emissions. <br> The tax is usually a fixed price per ton of CO<sub>2</sub> that is emitted for a certain activity or product. <br></p><p> In addition to cutting emissions, the money collected by the carbon tax can be used to address social injustice. For example by giving it back to citizens as a dividend. It could also be used to support additional projects that fight climate change by reinvesting the money.<br><p> The government has various possibilities to design policies for a carbon tax. Imagine, therefore, that the U.S. Federal Government announces a referendum about the introduction of a carbon tax. <br> This carbon tax could vary in different features. These features as well as an example will be explained to you on the next page. <br> <br> Following that, we ask you to vote in 12 hypothetical referendums for or against the introduction of a carbon tax. <br></p>"

    # Task Example 
    Title_taskExample = "Instructions on your task - task example"
    example_taskExample = "This is how a hypothetical carbon tax referendum looks like in our task."
    intro_attributes = "These policies can vary in the following features: "
    list_attributes = "<ul><li> <b>Carbon pricing sector</b> <br> The tax could be imposed in <b>general/ton of CO<sub>2</sub></b> on all emissions. That means that for each product the associated CO<sub>2</sub> emissions would be calculated and a tax would be applied. Alternatively, the tax could be imposed on products of <b>meat and dairy/ton of CO<sub>2</sub></b>, or on products related to <b>energy production/ton of CO<sub>2</sub></b>. The latter would include, for example, electricity, petrol or heating oil. </li> <br><li> <b>Price per ton of CO<sub>2</sub> emissions</b> <br> Depending on the price per ton of CO<sub>2</sub> emissions, different outcomes in terms of carbon neutrality can be achieved. Carbon-neutral means, that no more CO<sub>2</sub> emissions are released into the atmosphere than can be taken out again. With a price of <b>$60 per ton of CO<sub>2</sub></b> carbon neutrality could be achieved past mid-century, around 2060. With a price of <b>$120 per ton of CO<sub>2</sub></b> carbon neutrality could be achieved by mid-century, around 2050. </li> <br> <li> <b>Revenue mechanism </b> <br> The money collected (revenue) by imposing a tax on carbon emissions could be either <b>paid back as a dividend</b> to each citizen. This would mean that social injustice could be balanced out, as people who cause high CO<sub>2</sub> emissions would also have to pay more tax, but the dividend would be the same for all citizens. In this way, people who cause few CO<sub>2</sub> emissions benefit from the tax contributions of those who emit a lot. Another option would be, that the revenue would be <b>reinvested in Carbon Dioxide Removal technologies</b>. These novel technologies are able to remove CO<sub>2</sub> from the atmosphere and therefore contribute to CO<sub>2</sub> reduction.</li> <br><li> <b>Implementation timing</b> <br> The start of the policy packages could be <b>in 1 year</b> or <b>in 7 years</b>. The duration and effects (revenue, additional taxes) pertain to a period of 30 years after the introduction of the measures. This refers to the starting point for the concrete implementation of the decided measures. That means if a policy package is implemented in 5 years (by the end of 2027), CO<sub>2</sub> emissions will only be reduced from that point onward, and additional taxes will also be imposed from that time.</li></ul>"
    explain_Example = "<i>That is, in the example above, the government proposes a carbon tax policy where CO<sub>2</sub> emissions in <b>general/ton</b> are taxed with a price of <b>$120 per ton</b>. The collected money would be used for <b>Investment in Carbon Dioxide Removal</b> technology and the tax would start <b>in 7 years</b> from now.</i> <br>"
    instr_continue = "You will now be presented with <b>12 hypothetical policy proposals</b> one after another. <br> For each of them you can vote with <b>Yes</b> or <b>No</b>, whether you would accept them or not. <br> Please look at each policy proposal carefully and take some time to make your vote. <br> The order in which the 4 features are presented will change across the 12 examples you will see."


    next = "Next"
    