class Lexicon:
    next = "下一个"
    #Policy task
    title_taskPage = "碳税政策汇编"
    instr_taskPage = "政府提出了以下碳税政策方案:"
    accept_yes = "是的"
    accept_no = "不"
    would_accept = "你会支持这个政策主张吗？"
    # Help button
    helpText = "查看属性汇总，请点击"
    helpButton = "帮助"
    helpSector = "行业"
    helpSectorText = "将征税的行业：<b>一般对所有排放</b>,<b>肉类和乳制品</b>或<b>能源生产</b>" 
    helpTiming = "实施时间"
    helpTimingText = "政策开始：<b>1 年内</b>或<b>7 年内</b>" 
    helpPrice = "价格"
    helpPriceText = "每排放一吨 二氧化碳 增加的价格：<b>￥234</b> 或 <b>￥467</b>" 
    helpRevenue = "收入机制"
    helpRevenueText = "税收所收取的资金将如何使用：<b>向公民发放红利</b>或<b>投资于二氧化碳去除</b>"
    helpClose = "点击此处关闭窗口"